name: yell_lander
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0 # Use the latest version
  flutter_recorder: ^1.1.1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#2196F3"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
